---

- name: GRAFANA | Configuring service
  systemd:
    name: grafana-server
    state: "{{ grafana_service_state }}"
    enabled: "{{ grafana_service_enabled }}"
    daemon_reload: yes

- name: GRAFANA | Wait for service listening
  wait_for:
    host: "{{ grafana_host }}"
    port: "{{ grafana_port }}"
    state: "{{ grafana_service_state }}"
    timeout: "{{ grafana_service_timeout }}"

- name: GRAFANA | Wait for health respond 200
  uri:
    url: "http://{{ ansible_nodename }}:{{ grafana_port }}/api/health"
    status_code: "200"
    method: GET
    headers:
      Accept: application/json
  register: result
  until: result.status == 200
  retries: "{{ grafana_service_timeout }}"
  delay: 1
