# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = "Europe/Madrid"
  end
 config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = 1024
    virtualbox.cpus = 2
  end

  config.vm.define "grafana" do |grafana|
    grafana.vm.box = "debian/jessie64"
    grafana.vm.hostname = "server"
    grafana.vm.network "private_network", ip:"10.0.0.2"
    grafana.vm.provision "ansible" do |ansible|
      ansible.galaxy_role_file = "requirements.yml"
      ansible.playbook = "main.yml"
      ansible.ask_vault_pass = true
      ansible.sudo = true
    end
  end

end
