---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: grafana
    groups:
      - grafana
    image: ${DOCKER_BASE_IMAGE:-debian:stretch-slim}
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - /run
      - /run/lock
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: ansible
