---

## MYSQL
mysql_root_password: secret
mysql_databases:
  - name: 'grafana'
    encoding: 'utf8'

mysql_users:
  - name: 'grafana'
    password: 'grafana'
    priv:
      - grafana.*:ALL

mysql_datadir: /var/lib/mysql

mysql_required_libs:
  - python3-mysqldb
  - python-pymysql

mysql_server_version: mysql-5.7
mysql_share_dir: /usr/share/mysql
mysql_protect_system: false
mysql_protect_home: false
mysql_private_devices: false

## GRAFANA
grafana_version: 8.2.0
grafana_port: 8081
grafana_organisation: The Organisation

grafana_user: grafana
grafana_group: grafana

grafana_data_path: /var/lib/grafana

grafana_plugins_path: "{{ grafana_data_path }}/plugins"
grafana_log_path: /var/log/grafana


grafana_plugins:
  - name: camptocamp-prometheus-alertmanager-datasource
    version: 0.0.8
    state: present

grafana_plugins_allow_loading_unsigned_plugins: 'camptocamp-prometheus-alertmanager-datasource'

grafana_service_template_path: grafana-server.service.j2

grafana_documentation_link: "http://docs.grafana.org"
grafana_max_files: 10000
grafana_exec_name: grafana-server
grafana_bin_path: /usr/sbin
grafana_options:
  - --config=${CONF_FILE}
  - --pidfile=${PID_FILE_DIR}/grafana-server.pid
  - --packaging=deb
  - cfg:default.paths.logs=${LOG_DIR}
  - cfg:default.paths.data=${DATA_DIR}
  - cfg:default.paths.plugins=${PLUGINS_DIR}
  - cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR}
grafana_working_directory: /usr/share/grafana
grafana_private_tmp: false
